// <auto-generated />
namespace GW2FALFG.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixVoiceChatNormalization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixVoiceChatNormalization));
        
        string IMigrationMetadata.Id
        {
            get { return "201302222154412_FixVoiceChatNormalization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
