// <auto-generated />
namespace GW2FALFG.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NormalizeWithManyToManyVoiceChat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NormalizeWithManyToManyVoiceChat));
        
        string IMigrationMetadata.Id
        {
            get { return "201302222025475_NormalizeWithManyToManyVoiceChat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
